version: "3"
services:
################################################################################
  app:
    build: ./Dockerfiles/uwsgi
    volumes:
      - ./app:/app
      - socket:/tmp
    command: uwsgi --ini /app/app.ini
    restart: always
################################################################################
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - socket:/tmp
    links:
      - app
    restart: always
################################################################################
volumes:
  socket:
